// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxD5OdPr2Dsaf2ZZqx2Cb16VjK6Nn-ec',
    appId: '1:281790011079:web:866c108a95db0ea21650e2',
    messagingSenderId: '281790011079',
    projectId: 'e-commerse-app-650d7',
    authDomain: 'e-commerse-app-650d7.firebaseapp.com',
    storageBucket: 'e-commerse-app-650d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJSgD4WaDSapigFiid9mL9gzuzA5S1lg',
    appId: '1:281790011079:android:1afc52e8c7075de31650e2',
    messagingSenderId: '281790011079',
    projectId: 'e-commerse-app-650d7',
    storageBucket: 'e-commerse-app-650d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ZJFFevdn22KAhUNiShvVfWmMBF47Z84',
    appId: '1:281790011079:ios:1ad587286f5d16571650e2',
    messagingSenderId: '281790011079',
    projectId: 'e-commerse-app-650d7',
    storageBucket: 'e-commerse-app-650d7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ZJFFevdn22KAhUNiShvVfWmMBF47Z84',
    appId: '1:281790011079:ios:1ad587286f5d16571650e2',
    messagingSenderId: '281790011079',
    projectId: 'e-commerse-app-650d7',
    storageBucket: 'e-commerse-app-650d7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRxD5OdPr2Dsaf2ZZqx2Cb16VjK6Nn-ec',
    appId: '1:281790011079:web:3f8f30f3c2e368491650e2',
    messagingSenderId: '281790011079',
    projectId: 'e-commerse-app-650d7',
    authDomain: 'e-commerse-app-650d7.firebaseapp.com',
    storageBucket: 'e-commerse-app-650d7.firebasestorage.app',
  );
}
